### ISSUE TITLE
fsl.FILMGLS throws strange error:-r: Option doesn't exist!

### ISSUE THREAD

**Issue by SebastianSpeer** [nipy/nipype#2281] opened 2017-11-15 17:21 UTC
I've just tried to use fsl.FILMGLS() for the first time and tried a lot of different inputs and I always get the same error:

> RuntimeError: Command:
> film_gls -rn results /data/sebastian/SPD/Preprocessed2/fixed_tr/20171105_115019_017.nii /data/sebastian/SPD/Preprocessed2/sub010/design/run1/new_design.mat 0.000000
> Standard output:
> 
> Standard error:
>  -r: Option doesn't exist!
>  try: film_gls --help
>  Return code: 1
>  Interface FILMGLS failed to run. 

This is the simplest version of the code:

```
modelestimate = pe.Node(fsl.FILMGLS(),name='modelestimate')
modelestimate.inputs.in_file='/data/sebastian/SPD/Preprocessed2/fixed_tr/20171105_115019_017.nii'
modelestimate.inputs.design_file='/data/sebastian/SPD/Preprocessed2/sub010/design/run1/new_design.mat'
modelestimate.run()
```

Does somebody know what the issue may be?

**Comment by djarecka** [comment] 2017-11-15 18:02
@SebastianSpeer when I'm trying to run something similar my command starts from `film_gls --rn` and not from `film_gls -rn`.

Can you please share with us the platform details (output from `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`) and the execution environment.

**Comment by SebastianSpeer** [comment] 2017-11-15 18:22
@djarecka I'm running nipype version 0.13.1.
When trying to run the nipype.get_info()
I get the following error:

> InterpolationSyntaxErrorTraceback (most recent call last)
> ipython-input-3-1eb6ba6091a6> in <module>()
>       1 import nipype
>       2 print(nipype.__version__)
> ----> 3 print(nipype.get_info())
> 
> /home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/__init__.pyc in get_info()
>      45 def get_info():
>      46     """Returns package information"""
> ---> 47     return _get_pkg_info(os.path.dirname(__file__))
>      48 
>      49 from .pipeline import Node, MapNode, JoinNode, Workflow
> 
> /home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.pyc in get_pkg_info(pkg_path)
>      86        with named parameters of interest
>      87     '''
> ---> 88     src, hsh = pkg_commit_hash(pkg_path)
>      89     import networkx
>      90     import nibabel
> 
> /home/sebastian/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.pyc in pkg_commit_hash(pkg_path)
>      54         cfg_parser = configparser.ConfigParser()
>      55     cfg_parser.read(pth)
> ---> 56     archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
>      57     if not archive_subst.startswith('$Format'):  # it has been substituted
>      58         return 'archive substitution', archive_subst
> 
> /home/sebastian/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.pyc in get(self, section, option, **kwargs)
>     809         else:
>     810             return self._interpolation.before_get(self, section, option, value,
> --> 811                                                   d)
>     812 
>     813     def _get(self, section, conv, option, **kwargs):
> 
> /home/sebastian/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.pyc in before_get(self, parser, section, option, value, defaults)
>     382     def before_get(self, parser, section, option, value, defaults):
>     383         L = []
> --> 384         self._interpolate_some(parser, option, L, value, section, defaults, 1)
>     385         return ''.join(L)
>     386 
> 
> /home/sebastian/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.pyc in _interpolate_some(self, parser, option, accum, rest, section, map, depth)
>     432                     option, section,
>     433                     "'%%' must be followed by '%%' or '(', "
> --> 434                     "found: %r" % (rest,))
>     435 
>     436 
> 
> InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'

**Comment by SebastianSpeer** [comment] 2017-11-16 13:14
So it means it is a compatibility issue?

**Comment by djarecka** [comment] 2017-11-16 13:34
the problem with `get_info` should be fixed in #2282. 

I'm just checking the `FSL` problem and IMO it can be related that the version `FSL` is not properly recognized. Do you know what is your version of `FSL`?

Can you also see what `nipype` is thinking about your version, e.g.:

```
from nipype.interfaces.fsl.base import Info
Info.version()
```

**Comment by djarecka** [comment] 2017-11-16 13:37
also, I see you have Linux platform. Any chances you're running within a Docker container?

**Comment by SebastianSpeer** [comment] 2017-11-16 13:37
```
from nipype.interfaces.fsl.base import Info
Info.version()
```
`u'5.0.9'`

**Comment by SebastianSpeer** [comment] 2017-11-16 13:41
No, I am running on a virtual machine.

**Comment by djarecka** [comment] 2017-11-16 14:22
It looks like indeed `Info.version` works ok, but I still have a feeling that you might not go inside this `if block` (https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/model.py#L694)

Maybe you can check one more thing:

```
from nipype.interfaces.fsl.base import Info
from distutils.version import LooseVersion
print(LooseVersion(Info.version()) > LooseVersion('5.0.6'))
print(Info.version() and LooseVersion(Info.version()) > LooseVersion('5.0.6'))
```

btw. Is it a way to get your VM?

**Comment by SebastianSpeer** [comment] 2017-11-16 15:03
This is the output:

```
from nipype.interfaces.fsl.base import Info
from distutils.version import LooseVersion
print(LooseVersion(Info.version()) > LooseVersion('5.0.6'))
print(Info.version() and LooseVersion(Info.version()) > LooseVersion('5.0.6'))
```
```
True
True
```

I don't understand your last question. Can you elaborate?

**Comment by djarecka** [comment] 2017-11-16 18:05
@SebastianSpeer  the reason why I'm asking for VM is that I'm not sure how can I reproduce your error. I can try to set Docker container if you tell me details of your environment, but it could be easier if you share with me the snapshot/image of your VM.

How do you run your VM? Do you use publicly available image that I can download and use.

**Comment by djarecka** [comment] 2017-11-16 18:08
@SebastianSpeer there is also one more thing that you can try, just try to install our newest version from master branch `pip install -U https://github.com/nipy/nipype/archive/master.zip`.

I'm not saying that this will help (don't see any recent changes that could affect the interface), but it's worth trying IMO.

**Comment by SebastianSpeer** [comment] 2017-11-16 18:17
I have tried it with the newest version from the master branch, but it also resulted in the same error.
I am happy to share the VM but I am relatively new to working with VMs so I am not sure how to share it. IF you tell me how, I can try.
The VM runs on SurfSara which is a HPC in the netherlands.

Otherwise what other details would you need?

**Comment by djarecka** [comment] 2017-11-16 19:35
Let's test one more thing:

```
from nipype.interfaces.fsl import FILMGLS
film_gls = FILMGLS()
print(film_gls.version)
print(film_gls.input_spec)
```

Regarding VM, I also don't use VM too often, but we can try to figure out together how to create a snapshot. We should probably know which software are you using to run your VM, is it `Virual Box`? 
Also if you have access to some local admins they can probably tell you how to create snapshot.

**Comment by SebastianSpeer** [comment] 2017-11-17 11:12
@djarecka  This is the output of the code:

```
from nipype.interfaces.fsl import FILMGLS
film_gls = FILMGLS()
print(film_gls.version)
print(film_gls.input_spec)
```

```

5.0.9
<class 'nipype.interfaces.fsl.model.FILMGLSInputSpec'>
```

Regarding the VM I have contacted the local admin and will let you know as soon as I know more.

If this fails, what information do you need to create the docker?

**Comment by SebastianSpeer** [comment] 2017-11-17 14:27
@djarecka  The software that is used to run the VM is: Opennebula 5.2.1.

According to the helpdesk of SurfSara one way to share the VM is if you would generate an ssh key-pair - https://doc.hpccloud.surfsara.nl/SSHkey and send me the public key. I would then add his public key to the ~/.ssh/authorized_keys in the VM. 

Would that work?

**Comment by djarecka** [comment] 2017-11-17 15:13
@SebastianSpeer 
Re your error:
This is what I expected that for some reason nipype is using older version of `input_spec`: `nipype.interfaces.fsl.model.FILMGLSInputSpec`, but I really don't know how this can happen since nipype verifies your `FSL` version correctly... 

Thanks for checking with your admin, let me read about it and will come back to you. I already tried a few different setting to check it and never seen the problem, so it might be interesting to check what is really happening. 
But two more things that you can print for me, so might try to reproduce:
 - your linux distribution: you can try `lsb_release --all` or `python -c "import platform; print platform.dist()"`
 - environmental variables: `printenv`

In the meantime, I'd just check if you can run your example with`Python3`. Unless you really need Python 2 that could be a good idea regardless of the current issue.

**Comment by SebastianSpeer** [comment] 2017-11-17 15:22
Here the output of  ` python -c "import platform; print platform.dist()"
`

`('debian', 'jessie/sid', '')`


This is the output of printenv:
```
XDG_VTNR=7
SSH_AGENT_PID=2971
XDG_SESSION_ID=c3
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/adminubuntu
SELINUX_INIT=YES
SESSION=xubuntu
GLADE_PIXMAP_PATH=:
HOST=ip-145-100-58-103
TERM=xterm
XDG_MENU_PREFIX=xfce-
SHELL=/bin/bash
SSH_AGENT_LAUNCHER=upstart
FSLMULTIFILEQUIT=TRUE
WINDOWID=31464658
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/2811
POSSUMDIR=/usr/share/fsl/5.0
GROUP=adminubuntu
USER=sebastian
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
GLADE_MODULE_PATH=:
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
HOSTTYPE=x86_64-linux
SSH_AUTH_SOCK=/tmp/ssh-rwPFpOsWSBah/agent.2969
SESSION_MANAGER=local/ip-145-100-58-103:@/tmp/.ICE-unix/3074,unix/ip-145-100-58-103:/tmp/.ICE-unix/3074
DEFAULTS_PATH=/usr/share/gconf/xubuntu.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-xubuntu:/usr/share/upstart/xdg:/etc/xdg:/etc/xdg
MAIL=/var/mail/sebastian
DESKTOP_SESSION=xubuntu
PATH=/home/sebastian/anaconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/adminubuntu
JOB=dbus
LANG=en_US.UTF-8
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/xubuntu.mandatory.path
FSLTCLSH=/usr/bin/tclsh
FSLMACHINELIST=
IM_CONFIG_PHASE=1
FSLREMOTECALL=
GDMSESSION=xubuntu
FSLWISH=/usr/bin/wish
SESSIONTYPE=
SHLVL=2
HOME=/home/sebastian
FSLBROWSER=/etc/alternatives/x-www-browser
XDG_SEAT=seat0
OSTYPE=linux
LANGUAGE=en_US
UPSTART_INSTANCE=
VENDOR=unknown
MACHTYPE=x86_64
UPSTART_EVENTS=started xsession
LOGNAME=sebastian
FSLDIR=/usr/share/fsl/5.0
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-lBlkRdivJa
XDG_DATA_DIRS=/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share
LESSOPEN=| /usr/bin/lesspipe %s
TEXTDOMAIN=im-config
INSTANCE=
UPSTART_JOB=startxfce4
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0.0
GLADE_CATALOG_PATH=:
FSLLOCKDIR=
XDG_CURRENT_DESKTOP=XFCE
FSLOUTPUTTYPE=NIFTI_GZ
LESSCLOSE=/usr/bin/lesspipe %s %s
TEXTDOMAINDIR=/usr/share/locale/
XAUTHORITY=/home/adminubuntu/.Xauthority
COLORTERM=xfce4-terminal
_=/usr/bin/printenv
```

**Comment by djarecka** [comment] 2017-11-17 15:25
@SebastianSpeer - I know I'm asking you to check many things, but I was just discussing with @mgxd our conversation and we stared wondering if you're sure that you're running `0.13.1.` version of nipype. I believe that you installed it, but it could be some conflict.

At the beginning I asked you to run `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"` but you got an error  with `nipype.get_info()` and not sure if you ever run the second part, so can you please check for me this shorter version now:
`python -c "import nipype; print(nipype.__version__)"`

**Comment by SebastianSpeer** [comment] 2017-11-17 15:29
No worries, I am very happy about your help, so I'll check as many things as needed.

Currently I am running the version from the master file:

`python -c "import nipype; print(nipype.__version__)"`
`1.0.0-dev`

**Comment by satra** [comment] 2017-11-17 19:00
@SebastianSpeer  - this is quite weird, while you setup @djarecka public key could you please execute this:

```python
from nipype.pkg_info import VERSION
from nipype.interfaces.fsl import FILMGLS, Info
import sys
print(sys.version)
film_gls = FILMGLS()
print(film_gls.version)
print(Info.version())
print(film_gls.input_spec)
print(VERSION)
```

**Comment by SebastianSpeer** [comment] 2017-11-20 08:47
@satra the output to:

`from nipype.pkg_info import VERSION
from nipype.interfaces.fsl import FILMGLS, Info
import sys
print(sys.version)
film_gls = FILMGLS()
print(film_gls.version)
print(Info.version())
print(film_gls.input_spec)
print(VERSION)`

is: 


`2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
5.0.9
5.0.9
<class 'nipype.interfaces.fsl.model.FILMGLSInputSpec'>
1.0.0-dev`

@djarecka is there any progress regarding the ssh key?
I asked my local admin to create a copy of my vm which I could share as well.

**Comment by djarecka** [comment] 2017-11-20 13:50
@SebastianSpeer unfortunately your answers to @satra questions looks again pretty weird to me...

 if you have copy of your vm that you can share, that might be the best option, so more people can look into it on local machines. I can give you my public key, but my understanding is that you would give me a full root access to your VM, is that  works for you? Of course, I can promise to not do anything stupid without your permission etc., but just wasn't sure if this is the best option...

**Comment by SebastianSpeer** [comment] 2017-11-20 13:52
Is it best to share it via email ? I would send you the IP to the VM and the password to log in.

**Comment by djarecka** [comment] 2017-11-20 19:36
@SebastianSpeer thank you for sharing your VM. I tested your environment and I noticed that you probably always run `import nipype_init; nipype_init.init()` in jupyter notebook before running any fsl examples. The script doesn't work correctly, and the line `res = subprocess.call('/etc/fsl/5.0/fsl.sh',shell=True)` doesn't setup the shell correctly. In fact, if you run it using python interpreter (not inside jupyter notebook, you get an error).

So the solution would be to remove  the line `res = subprocess.call('/etc/fsl/5.0/fsl.sh',shell=True)` from `nipype_init.py` (the sam for freesurfer) and run  `'/etc/fsl/5.0/fsl.sh'` script before running python script or opening  jupyter notebook.

**Comment by djarecka** [comment] 2017-11-20 19:37
Also you should avoid adding path like this `sys.path.append('/home/sebastian/anaconda2/lib/python2.7/site-packages')`. Python should find all packages that you installed.

**Comment by SebastianSpeer** [comment] 2017-11-21 18:20
@djarecka Thanks for your help. I changed the permissions of the fsl folders so that   subprocess.call('/etc/fsl/5.0/fsl.sh',shell=True) does not result in an error anymore.
I still receive an error from the fsl.FILMGLS().

It would have also been strange that all other functions dependent on fsl run fine if the FSL environment was set incorrectly. So I assume the problem must be something else?

**Comment by djarecka** [comment] 2017-11-21 18:43
@SebastianSpeer  : just try `source /etc/fsl/5.0/fsl.sh` before opening jupyter notebook or running your script and it will work

**Comment by djarecka** [comment] 2017-11-21 18:45
the easies way to see a difference would be to go to python interpreter and run:
```
import nipype.interfaces.fsl as fsl
fsl_interf = fsl.FILMGLS()
fsl_interf.input_spec
```
if you don't source the fsl script nipype will not correctly set the inpu_spec (it's confused about the version)

**Comment by SebastianSpeer** [comment] 2017-11-23 13:22
I finally got it to work now! Thank you so much for your help!

**Closed** 2017-11-23 13:23 UTC
