### ISSUE TITLE
Nipype Failures On Installation

### ISSUE THREAD

**Issue by kevnmr** [nipy/nipype#1975] opened 2017-04-27 13:56 UTC
### Summary
Hi

I cannot get the 0 error 0 failures that i'm supposed to.
I got
Ran 17307 tests in 312.663s

FAILED (SKIP=21, errors=6, failures=3)

I followed this guide http://miykael.github.io/nipype-beginner-s-guide/installation.html
Please help as i'm not sure what i did wrong. Thank you.

### Actual behavior

======================================================================
ERROR: Failure: TypeError ('numpy.float64' object cannot be interpreted as an index
Interface SpecifySparseModel failed to run. )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/tests/test_modelgen.py", line 138, in test_modelgen_sparse
    res = s.run()
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/modelgen.py", line 408, in _run_interface
    self._generate_design()
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/modelgen.py", line 802, in _generate_design
    sparselist = self._generate_clustered_design(infolist)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/modelgen.py", line 783, in _generate_clustered_design
    reg, regnames = self._cond_to_regress(info, nscans)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/modelgen.py", line 751, in _cond_to_regress
    nscans)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/modelgen.py", line 655, in _gen_regress
    boxcar = np.zeros((50.0 * 1e3 / dt))
TypeError: 'numpy.float64' object cannot be interpreted as an index
Interface SpecifySparseModel failed to run. 

======================================================================
ERROR: Failure: TypeError ('numpy.float64' object cannot be interpreted as an index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/tests/test_splitmerge.py", line 30, in test_split_and_merge
    resdw, resmsk, resid = split_rois(dwfile, in_mask, roishape=(20, 20, 2))
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/algorithms/misc.py", line 1356, in split_rois
    droi = np.vstack((droi, np.zeros((fill, nvols), dtype=np.float32)))
TypeError: 'numpy.float64' object cannot be interpreted as an index

======================================================================
ERROR: Failure: InterpolationSyntaxError ('%' must be followed by '%' or '(', found: u'%h')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/tests/test_utils.py", line 342, in test_provenance
    psg = write_workflow_prov(eg, prov_base, format='all')
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/utils.py", line 1270, in write_workflow_prov
    prov_doc = ProvStore().add_results(result)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 376, in add_results
    for key, value in list(get_info().items()):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
    get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
    src, hsh = pkg_commit_hash(pkg_path)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
    archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
    "found: %r" % (rest,))
InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'

======================================================================
ERROR: Failure: ImportError (No module named mock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pipeline/plugins/tests/test_base.py", line 9, in <module>
    import mock
ImportError: No module named mock

======================================================================
ERROR: Failure: InterpolationSyntaxError ('%' must be followed by '%' or '(', found: u'%h')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/tests/test_provenance.py", line 18, in test_provenance
    ps.add_results(results)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 376, in add_results
    for key, value in list(get_info().items()):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
    get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
    src, hsh = pkg_commit_hash(pkg_path)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
    archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
    "found: %r" % (rest,))
InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'

======================================================================
ERROR: Failure: InterpolationSyntaxError ('%' must be followed by '%' or '(', found: u'%h')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/tests/test_provenance.py", line 32, in test_provenance_exists
    CommandLine('echo hello').run()
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1092, in run
    prov_record = write_provenance(results)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 244, in write_provenance
    ps.add_results(results)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 376, in add_results
    for key, value in list(get_info().items()):
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
    get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
    src, hsh = pkg_commit_hash(pkg_path)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
    archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
    "found: %r" % (rest,))
InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'

======================================================================
FAIL: Doctest: nipype.interfaces.bru2nii.Bru2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nipype.interfaces.bru2nii.Bru2
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/bru2nii.py", line 26, in Bru2

----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/bru2nii.py", line 34, in nipype.interfaces.bru2nii.Bru2
Failed example:
    converter.inputs.input_dir = "brukerdir"
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.interfaces.bru2nii.Bru2[2]>", line 1, in <module>
        converter.inputs.input_dir = "brukerdir"
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 169, in validate
        self.error(object, name, value)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
        value )
    TraitError: The 'input_dir' trait of a Bru2InputSpec instance must be an existing directory name, but a value of 'brukerdir' <type 'str'> was specified.
----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/bru2nii.py", line 35, in nipype.interfaces.bru2nii.Bru2
Failed example:
    converter.cmdline  # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.interfaces.bru2nii.Bru2[3]>", line 1, in <module>
        converter.cmdline  # doctest: +ELLIPSIS
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1608, in cmdline
        self._check_mandatory_inputs()
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 940, in _check_mandatory_inputs
        raise ValueError(msg)
    ValueError: Bru2 requires a value for input 'input_dir'. For a list of required inputs, see Bru2.help()

======================================================================
FAIL: Doctest: nipype.workflows.fmri.spm.preprocess.create_DARTEL_template
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nipype.workflows.fmri.spm.preprocess.create_DARTEL_template
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 227, in create_DARTEL_template

----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 234, in nipype.workflows.fmri.spm.preprocess.create_DARTEL_template
Failed example:
    preproc = create_DARTEL_template()
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_DARTEL_template[0]>", line 1, in <module>
        preproc = create_DARTEL_template()
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 256, in create_DARTEL_template
        segment = pe.MapNode(spm.NewSegment(),
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/preprocess.py", line 901, in __init__
        _local_version = SPMCommand().version
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/base.py", line 285, in version
        use_mcr=self.inputs.use_mcr)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/base.py", line 186, in version
        out = mlab.run()
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1092, in run
        prov_record = write_provenance(results)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 244, in write_provenance
        ps.add_results(results)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 376, in add_results
        for key, value in list(get_info().items()):
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
        get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
        src, hsh = pkg_commit_hash(pkg_path)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
        archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
        d)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
        self._interpolate_some(parser, option, L, value, section, defaults, 1)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
        "found: %r" % (rest,))
    InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'
----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 235, in nipype.workflows.fmri.spm.preprocess.create_DARTEL_template
Failed example:
    preproc.inputs.inputspec.structural_files = [os.path.abspath('s1.nii'), os.path.abspath('s3.nii')]
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_DARTEL_template[1]>", line 1, in <module>
        preproc.inputs.inputspec.structural_files = [os.path.abspath('s1.nii'), os.path.abspath('s3.nii')]
    NameError: name 'preproc' is not defined
----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 236, in nipype.workflows.fmri.spm.preprocess.create_DARTEL_template
Failed example:
    preproc.inputs.inputspec.template_prefix = 'Template'
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_DARTEL_template[2]>", line 1, in <module>
        preproc.inputs.inputspec.template_prefix = 'Template'
    NameError: name 'preproc' is not defined

======================================================================
FAIL: Doctest: nipype.workflows.fmri.spm.preprocess.create_vbm_preproc
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nipype.workflows.fmri.spm.preprocess.create_vbm_preproc
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 133, in create_vbm_preproc

----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 141, in nipype.workflows.fmri.spm.preprocess.create_vbm_preproc
Failed example:
    preproc = create_vbm_preproc()
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_vbm_preproc[0]>", line 1, in <module>
        preproc = create_vbm_preproc()
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 172, in create_vbm_preproc
        dartel_template = create_DARTEL_template()
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 256, in create_DARTEL_template
        segment = pe.MapNode(spm.NewSegment(),
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/preprocess.py", line 901, in __init__
        _local_version = SPMCommand().version
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/base.py", line 285, in version
        use_mcr=self.inputs.use_mcr)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/spm/base.py", line 186, in version
        out = mlab.run()
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1092, in run
        prov_record = write_provenance(results)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 244, in write_provenance
        ps.add_results(results)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/utils/provenance.py", line 376, in add_results
        for key, value in list(get_info().items()):
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
        get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
        src, hsh = pkg_commit_hash(pkg_path)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
        archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
        d)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
        self._interpolate_some(parser, option, L, value, section, defaults, 1)
      File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
        "found: %r" % (rest,))
    InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'
----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 142, in nipype.workflows.fmri.spm.preprocess.create_vbm_preproc
Failed example:
    preproc.inputs.inputspec.fwhm = 8
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_vbm_preproc[1]>", line 1, in <module>
        preproc.inputs.inputspec.fwhm = 8
    NameError: name 'preproc' is not defined
----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 143, in nipype.workflows.fmri.spm.preprocess.create_vbm_preproc
Failed example:
    preproc.inputs.inputspec.structural_files = [os.path.abspath('s1.nii'), os.path.abspath('s3.nii')]
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_vbm_preproc[2]>", line 1, in <module>
        preproc.inputs.inputspec.structural_files = [os.path.abspath('s1.nii'), os.path.abspath('s3.nii')]
    NameError: name 'preproc' is not defined
----------------------------------------------------------------------
File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/workflows/fmri/spm/preprocess.py", line 144, in nipype.workflows.fmri.spm.preprocess.create_vbm_preproc
Failed example:
    preproc.inputs.inputspec.template_prefix = 'Template'
Exception raised:
    Traceback (most recent call last):
      File "/home/kevin/anaconda2/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest nipype.workflows.fmri.spm.preprocess.create_vbm_preproc[3]>", line 1, in <module>
        preproc.inputs.inputspec.template_prefix = 'Template'
    NameError: name 'preproc' is not defined

----------------------------------------------------------------------
Ran 17307 tests in 312.663s

FAILED (SKIP=21, errors=6, failures=3)

### Platform details:
please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/__init__.py", line 60, in <lambda>
    get_info = lambda: _get_pkg_info(os.path.dirname(__file__))
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 82, in get_pkg_info
    src, hsh = pkg_commit_hash(pkg_path)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/nipype/pkg_info.py", line 52, in pkg_commit_hash
    archive_subst = cfg_parser.get('commit hash', 'archive_subst_hash')
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 811, in get
    d)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 434, in _interpolate_some
    "found: %r" % (rest,))
backports.configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'

**Comment by satra** [comment] 2017-04-27 14:22
duplicate of #1970 - please see that thread.

**Closed by satra** 2017-04-27 14:22 UTC
