### ISSUE TITLE
Cannot view .pklz crash files

### ISSUE THREAD

**Issue by brownsarahm** [nipy/nipype#1542] opened 2016-07-18 20:22 UTC
I get the following error when I run nipype_display_crash

-bash: /usr/local/anaconda/bin/nipype_display_crash: /home/travis/miniconda/envs/testenv/bin/python: bad interpreter: No such file or directory

it appears there's a manually set local directory somewhere

**Comment by chrisfilo** [comment] 2016-07-18 20:24
Seems like a duplicate of #1227 :/

**Comment by oesteban** [comment] 2016-07-18 20:52
OMG :(

**Comment by satra** [comment] 2016-07-19 01:33
@brownsarahm - would you mind doing the following and let me know if you still have the issue. this shouldn't be happening with current nipype release.

`pip install --upgrade nipype`

**Comment by mgxd** [comment] 2017-03-09 16:27
this should be fixed

**Closed by mgxd** 2017-03-09 16:27 UTC
Labels: needs review
