### ISSUE TITLE
unify naming of in*file* arguments in AFNI interfaces to the rest of the suite

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#87] opened 2011-01-12 18:49 UTC
While the other interfaces use in_file, AFNI still has infile

Since it would break API, I guess it would be logical to aim for 0.4.0, thus I added a new label (hope it is ok)

 $> git grep '\Winfile.*File' 
 doc/devel/interface_specs.rst:    infile = File(exists=True,
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3drefit',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dresample',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dTstat',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dAutomask',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dvolreg',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dvolreg',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dZcutup',
 nipype/interfaces/afni/preprocess.py:    infile = File(desc = 'input file to 3dAllineate',

**Comment by djarecka** [comment] 2018-01-17 21:18
duplicate of #5. closing

**Closed by djarecka** 2018-01-17 21:18 UTC
