### ISSUE TITLE
AttributeError: module 'networkx' has no attribute 'to_scipy_sparse_matrix'

### ISSUE THREAD

**Issue by mikiminachx** [nipy/nipype#3543] opened 2023-02-05 06:07 UTC
### Summary
I was following the preprocessing example on [https://miykael.github.io/nipype_tutorial/notebooks/example_preprocessing.html](url) 
When I ran `preproc.run('MultiProc', plugin_args={'n_procs': 8})`, it gave me the attribute error message.
### Actual behavior
Here's the error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 1
----> 1 preproc.run('MultiProc', plugin_args={'n_procs': 8})

File ~/.local/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py:638, in Workflow.run(self, plugin, plugin_args, updatehash)
    636 if str2bool(self.config["execution"]["create_report"]):
    637     self._write_report_info(self.base_dir, self.name, execgraph)
--> 638 runner.run(execgraph, updatehash=updatehash, config=self.config)
    639 datestr = datetime.utcnow().strftime("%Y%m%dT%H%M%S")
    640 if str2bool(self.config["execution"]["write_provenance"]):

File ~/.local/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py:121, in DistributedPluginBase.run(self, graph, config, updatehash)
    119 self._prerun_check(graph)
    120 # Generate appropriate structures for worker-manager model
--> 121 self._generate_dependency_list(graph)
    122 self.mapnodes = []
    123 self.mapnodesubids = {}

File ~/.local/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py:437, in DistributedPluginBase._generate_dependency_list(self, graph)
    434 import networkx as nx
    436 self.procs, _ = topological_sort(graph)
--> 437 self.depidx = nx.to_scipy_sparse_matrix(
    438     graph, nodelist=self.procs, format="lil"
    439 )
    440 self.refidx = self.depidx.astype(int)
    441 self.proc_done = np.zeros(len(self.procs), dtype=bool)

AttributeError: module 'networkx' has no attribute 'to_scipy_sparse_matrix'
```

### Expected behavior
It should start running the preprocessing process
### Script/Workflow details

[https://miykael.github.io/nipype_tutorial/notebooks/example_preprocessing.html](url)
I followed everything from this example.

### Platform details:

The version of the packages:
networkx           3.0
scipy              1.10.0
nipype             1.8.5

```
{'commit_hash': '<not found>',
 'commit_source': '(none found)',
 'networkx_version': '3.0',
 'nibabel_version': '5.0.0',
 'nipype_version': '1.8.5',
 'numpy_version': '1.21.6',
 'pkg_path': '/Users/mekolau/.local/lib/python3.10/site-packages/nipype',
 'scipy_version': '1.10.0',
 'sys_executable': '/usr/local/fsl/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.10.9 | packaged by conda-forge | (main, Feb  2 2023, '
                '20:24:27) [Clang 14.0.6 ]',
 'traits_version': '6.3.2'}
```

### Execution environment

Python 3.10.9
using jupyter notebook to run

**Comment by effigies** [comment] 2023-02-05 14:25
Duplicate of #3530. This will be resolved in the next release. For now you can either downgrade networkx to <3 or install from `master`.

**Closed by effigies** 2023-02-05 14:25 UTC

**Comment by mikiminachx** [comment] 2023-02-05 14:54
> Duplicate of #3530. This will be resolved in the next release. For now you can either downgrade networkx to <3 or install from `master`.

Thank you:)
