### ISSUE TITLE
The trait 'converted_files' of a Dcm2niixOutputSpec .. is an existing file name, but the path ....nii.gz' does not exist 

### ISSUE THREAD

**Issue by yarikoptic** [nipy/nipype#2474] opened 2018-03-01 01:58 UTC
### Summary

Originally reported by @mvdoc against heudiconv as a problem which came up with an upgrade to 1.0.0 nipype: https://github.com/nipy/heudiconv/issues/150
I have decided to share here (as well) since seems might be just nipype specific:

here is the log:
```
INFO: Doing conversion using dcm2niix
INFO: Converting /tmp/pytest-of-yoh/pytest-8/test_scout_conversion0/Halchenko/Yarik/950_bids_test4/phantom1sid1/sub-phantom1sid1/ses-localizer/fmap/sub-phantom1sid1_ses-localizer_acq-3mm_phasediff (1 DICOMs) -> /tmp/pytest-of-yoh/pytest-8/test_scout_conversion0/Halchenko/Yarik/950_bids_test4/phantom1sid1/sub-phantom1sid1/ses-localizer/fmap . Converter: dcm2niix . Output types: ('nii.gz', 'dicom')
INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
INFO: [Node] Setting-up "convert" in "/home/yoh/.tmp/dcm2niix08ng94/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b n -z i -x n -t n -m n -f fmap -o /home/yoh/picts/mris/heudiconv -s n -v n /home/yoh/.tmp/dcm2niix08ng94/convert/1.3.12.2.1107.5.2.43.66112.2016101409263663466202201.dcm
INFO: stdout 2018-02-28T20:54:55.269700:Chris Rorden's dcm2niiX version v1.0.20171215 (OpenJPEG build) GCC7.2.0 (64-bit Linux)
INFO: stdout 2018-02-28T20:54:55.269700:Found 1 DICOM image(s)
INFO: stdout 2018-02-28T20:54:55.269700:Convert 1 DICOM as /tmp/dcm2niix08ng94/convert/fmap_e2 (64x64x1x1)
INFO: stdout 2018-02-28T20:54:55.269700:Warning: Check that 2D images are not mirrored.
INFO: stdout 2018-02-28T20:54:55.269700:Conversion required 0.000793 seconds (0.000790 for core code).
WARNING: [Node] Error on "convert" (/home/yoh/.tmp/dcm2niix08ng94/convert)
FAILED

================================================================================================================== FAILURES ==================================================================================================================
___________________________________________________________________________________________________________ test_scout_conversion ____________________________________________________________________________________________________________
tests/test_mvdoc.py:11: in test_scout_conversion
    runner(args)
heudiconv/cli/run.py:120: in main
    process_args(args)
heudiconv/cli/run.py:330: in process_args
    overwrite=args.overwrite,)
heudiconv/convert.py:194: in prep_conversion
    overwrite=overwrite,)
heudiconv/convert.py:278: in convert
    bids, tmpdir)
heudiconv/convert.py:403: in nipype_convert
    eg = convertnode.run()
/usr/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py:487: in run
    result = self._run_interface(execute=True)
/usr/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py:571: in _run_interface
    return self._run_command(execute)
/usr/lib/python2.7/dist-packages/nipype/pipeline/engine/nodes.py:668: in _run_command
    _save_resultfile(result, outdir, self.name)
/usr/lib/python2.7/dist-packages/nipype/pipeline/engine/utils.py:244: in save_resultfile
    result.outputs.set(**modify_paths(outputs, relative=True, basedir=cwd))
/usr/lib/python2.7/dist-packages/traits/util/deprecated.py:32: in wrapper
    return fn(*args, **kw)
/usr/lib/python2.7/dist-packages/traits/has_traits.py:1552: in set
    trait_change_notify=trait_change_notify, **traits)
/usr/lib/python2.7/dist-packages/traits/has_traits.py:1544: in trait_set
    setattr( self, name, value )
/usr/lib/python2.7/dist-packages/nipype/interfaces/base/traits_extension.py:341: in validate
    value = super(MultiPath, self).validate(object, name, newvalue)
/usr/lib/python2.7/dist-packages/traits/trait_types.py:2337: in validate
    return TraitListObject( self, object, name, value )
/usr/lib/python2.7/dist-packages/traits/trait_handlers.py:2313: in __init__
    raise excp
E   TraitError: The trait 'converted_files' of a Dcm2niixOutputSpec instance is an existing file name, but the path  '/tmp/dcm2niix08ng94/convert/fmap_e2.nii.gz' does not exist.

```
so, for some reason nipype expects output to be in the source directory of the data -- not the output (provided to dcm2niix with `-o`, although now I am confused why current directory was chosen as the target (but that sounds like heudiconv issue)

**Comment by yarikoptic** [comment] 2018-03-01 02:03
actually -- I do not think we specify output directory!  so it must be nipype which does (now)
```
$> grep output_dir /home/yoh/.tmp/dcm2niix08ng94/convert/_report/report.rst
* output_dir : <undefined>
```
so it is nipype which somehow manages to pass current directory "by default" may be?

**Comment by jacobtfisher** [comment] 2018-03-01 17:23
I am having this same issue. For me it seems to be an issue with the latest version of NiPype coupled with the latest version of dcm2niix. Whenever I spin up a container with  dcm2niix v1.0.20170724 (the one bundled with (MRICroGL) it works without issue.

**Comment by jacobtfisher** [comment] 2018-03-01 17:23
I am having this same issue. For me it seems to be an issue with the latest version of NiPype coupled with the latest version of dcm2niix. Whenever I spin up a container with  dcm2niix v1.0.20170724 (the one bundled with (MRICroGL) it works without issue.

**Comment by effigies** [comment] 2018-03-22 16:37
@yarikoptic @jacobtfisher @mvdoc Have any of you tried out #2498 to check whether it resolves your issues? This seems like a good thing to try to fix before the next release.

Also @yarikoptic, we're shooting for 1.0.2 on Monday, so if you want to let us know if there are any neurodebian issues, that'd be good.

**Comment by effigies** [comment] 2018-03-23 19:40
#2498 has been merged. Can any of you confirm whether your issue is resolved with the latest master?

**Comment by mvdoc** [comment] 2018-03-23 21:32
I can't seem to reproduce the problem I had in https://github.com/nipy/heudiconv/issues/150, so I guess we're good? but I'll let @yarikoptic give the definite answer

**Comment by mgxd** [comment] 2018-03-28 17:39
closing this for now, if it still comes up feel free to reopen

**Closed by mgxd** 2018-03-28 17:39 UTC

**Comment by ilkayisik** [comment] 2018-07-11 08:02
I see that this issue is closed but i have recently got this error when I try to use heudiconv (0.5.2-dev):
```TraitError: The trait 'converted_files' of a Dcm2niixOutputSpec instance is an existing file name, but the path&nbsp; '/private/var/folders/yz/g_3xm0ms2f583j1d7bd6bz8xvxx8gp/T/tmp7s9Jpw/convert/func.nii.gz' does not exist.```
I am working on a computer (OS X El Capitan) where I have restricted permissions .
I seem to overcome this problem when I exchange the tempdir with a path where I haveedit permissions in convert.py (line 399):
```convertnode.base_dir = "/Users/user/test/tmp"```
